### ISSUE TITLE
aborted problem

### ISSUE THREAD

**Issue by Shields602** [thealanjason/umat_finite_viscoelasticity#3]
Thank you for your report and code!
“DOUBLE PRECISION, DIMENSION(6) :: BTOTV” should be added inito your UMAT code

**Comment by thealanjason** [comment]
Hi @Shields602 

Thank you for reporting this issue. Could you please specify which particular UMAT file you are referrering to?

**Comment by thealanjason** [comment]
I now understand the issue. The voigt notation `BTOTV` of the tensor `BTOT` was planned to be used in the `SPRIND` (an ABAQUS specific) subroutine to get the principal values and directions of the `BTOT` in https://github.com/thealanjason/umat_finite_viscoelasticity/blob/aea9ea855f9b515be07b95b98ab645d43bf6a0c1/UMAT/VISC_OGDEN_1EL.for#L577. This however was dropped, in order to test the UMAT, even when ABAQUS was not avaialble. The alternate chosen was to make a copy of `BTOT` into `BTOT_` and then use the open source subroutine `DSYEVJ3`(included as part of the UMAT at the bottom) to calculate the principal values and directions.

I shall fix this by deleting the necessary lines.

**Comment by Shields602** [comment]
I see, thanks
